name: sproutquest
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  image_picker: ^1.0.4
  firebase_storage: ^12.4.5
  uuid: ^4.2.1
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test: # Replacing flutter_driver with integration_test
    sdk: flutter
  test: # You can keep this if you have unit tests

flutter:
  uses-material-design: true
  assets:
    - assets/images/