// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCCEyIP1LkFH8iBYfJCoj2Rk15CBBoT8',
    appId: '1:975679330564:web:309d21e83bca8171ee9851',
    messagingSenderId: '975679330564',
    projectId: 'sprout-quest',
    authDomain: 'sprout-quest.firebaseapp.com',
    storageBucket: 'sprout-quest.firebasestorage.app',
    measurementId: 'G-NXSQZ0YVLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALwUGT8Cd9s3vHQaX75ahZBjbOF-OG1OQ',
    appId: '1:975679330564:android:577b5874a4d711d8ee9851',
    messagingSenderId: '975679330564',
    projectId: 'sprout-quest',
    storageBucket: 'sprout-quest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhybNcLz_tjAOP2zVImPBKU2qbviEXPYU',
    appId: '1:975679330564:ios:8db0c24aa1345672ee9851',
    messagingSenderId: '975679330564',
    projectId: 'sprout-quest',
    storageBucket: 'sprout-quest.firebasestorage.app',
    iosBundleId: 'com.example.sproutquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhybNcLz_tjAOP2zVImPBKU2qbviEXPYU',
    appId: '1:975679330564:ios:8db0c24aa1345672ee9851',
    messagingSenderId: '975679330564',
    projectId: 'sprout-quest',
    storageBucket: 'sprout-quest.firebasestorage.app',
    iosBundleId: 'com.example.sproutquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCCEyIP1LkFH8iBYfJCoj2Rk15CBBoT8',
    appId: '1:975679330564:web:c65e2d38f5855a51ee9851',
    messagingSenderId: '975679330564',
    projectId: 'sprout-quest',
    authDomain: 'sprout-quest.firebaseapp.com',
    storageBucket: 'sprout-quest.firebasestorage.app',
    measurementId: 'G-434QFR0DM3',
  );

}